// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWVOGzpJudbKjSKzgnWmTPL8pqDMjaOVw',
    appId: '1:542875029943:android:872dc64437d6d1c88a1832',
    messagingSenderId: '542875029943',
    projectId: 'kids-learning-app-303cc',
    storageBucket: 'kids-learning-app-303cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLJ0g10FIFIRQkyKAHer6a0qMLQtnqeQ',
    appId: '1:542875029943:ios:0aa3719e7275bdad8a1832',
    messagingSenderId: '542875029943',
    projectId: 'kids-learning-app-303cc',
    storageBucket: 'kids-learning-app-303cc.firebasestorage.app',
    iosBundleId: 'com.example.kids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKyamlJNJaFodN5LJ5BSEzTpU2QoqlMZs',
    appId: '1:542875029943:web:f985be6dc9967e418a1832',
    messagingSenderId: '542875029943',
    projectId: 'kids-learning-app-303cc',
    authDomain: 'kids-learning-app-303cc.firebaseapp.com',
    storageBucket: 'kids-learning-app-303cc.firebasestorage.app',
    measurementId: 'G-9YQ7LJ65XH',
  );
}
